### PR TITLE
Refactored to add EE3 support

### PR DESCRIPTION
**Pull request by sparkison**
Just had a site where I needed support for EE3. Figured I'd create a pull request to share the love with any other users that may have a need for it ;)

### CODE REVIEW

**Comment by b3nhartl3y** [comment]
Thanks massively for updating this plugin Shaun. I am able to get country code but the conditionals aren't functioning, did you manage to get them to work?

**Comment by sparkison** [comment]
If I remember correctly, the conditionals were working, but I could be wrong. It's been a minute since I implemented this ;)

I'll take a look and see if I see anything obvious.

**Comment by optima-ben** [comment]
Hi Shaun, any luck with the conditionals? Are they working for you?

**Comment by proimage** [comment]
Hey all, I'm doing some housecleaning on my GitHub account, so I'm merging this and I'd like to archive the repo, too. Before I do so, if anyone wants to take on being a official new home for this, let me know and I'll update the readme to direct people there.

**Pull request merged**
